apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  heroes-api-deployment
spec:
  paused: false
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: snavarropino/heroesapi:v1
        name: heroes-api
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
        - name: ConnectionStrings__herosConnection
          value: "server=heroes-sql-svc;Database=heroes;User ID=sa;Password=MiTemporal#1"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Cors__0
          value: "http://heroes-aks.westeurope.cloudapp.azure.com"
        readinessProbe:
          httpGet:
             path: /
             port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: heroes-api-svc
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: http