apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  heroes-sql-deployment
spec:
  paused: false
  replicas: 1
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: MiTemporal#1
---
apiVersion: v1
kind: Service
metadata:
  name: heroes-sql-svc
spec:
  type: LoadBalancer
  selector:
    app: sql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
